initialize robinson
adrianursu/campion.edu.ro-arhiva pull request #4
Opened 2020-10-20 18:24 UTC by adrianursu

2020-10-21 19:09 UTC, danielursuu requested changes

2020-10-21 19:09 UTC, danielursuu commented on robinson/ronbinson.cpp
> +		}
Move in a new function, for instance modifyPosition(l,c). Pay attention on parameters, by reference

2020-10-21 19:09 UTC, danielursuu commented on robinson/ronbinson.cpp
> +void calculateMap()
Change the name of the function. outputPositions() sounds ok to me

2020-10-21 19:09 UTC, danielursuu commented on robinson/tempCodeRunnerFile.cpp
> +void writeMatrix()
Delete this file. I don t know how it was generated

2020-10-21 19:09 UTC, danielursuu commented on robinson/ronbinson.cpp
> +
Close the input stream

2020-10-21 19:09 UTC, danielursuu commented on robinson/ronbinson.cpp
> +	}
Close the output stream

2020-10-21 19:09 UTC, danielursuu commented on robinson/robinson.in
> +5 64 3 2
Keep the input data

2020-10-21 19:09 UTC, danielursuu commented on robinson/robinson.out
> +3 2
Keep the output data from campion.edu

2020-10-21 19:09 UTC, danielursuu commented on robinson/ronbinson.cpp
> +int m, n, a[21][21], c, l;
The declaration of Arrays and matrixes keep on separated lines instead of the same line with other simple variables

2020-10-21 19:12 UTC, adrianursu commented
Gotcha boss

On Wed, 21 Oct 2020, 22:10 danielursuu, <notifications@github.com> wrote:

> *@danielursuu* requested changes on this pull request.
> ------------------------------
>
> In robinson/ronbinson.cpp
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509589125>
> :
>
> > +		switch (temp % 4)
> +		{
> +		case 0:
> +			l--;
> +			break;
> +		case 1:
> +			c++;
> +			break;
> +		case 2:
> +			l++;
> +			break;
> +		case 3:
> +			c--;
> +			break;
> +		}
>
> Move in a new function, for instance modifyPosition(l,c). Pay attention on
> parameters, by reference
> ------------------------------
>
> In robinson/ronbinson.cpp
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509591296>
> :
>
> > +		a[1][i] = n + i - 1;
> +	}
> +}
> +
> +void initializeRestOfMatrix()
> +{
> +	for (int i = 2; i <= m; i++)
> +	{
> +		for (int j = 2; j <= m; j++)
> +		{
> +			a[i][j] = (a[i - 1][j] + a[i][j - 1]) % 1000;
> +		}
> +	}
> +}
> +
> +void calculateMap()
>
> Change the name of the function. outputPositions() sounds ok to me
> ------------------------------
>
> In robinson/tempCodeRunnerFile.cpp
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509591992>
> :
>
> > @@ -0,0 +1,11 @@
> +void writeMatrix()
>
> Delete this file. I don t know how it was generated
> ------------------------------
>
> In robinson/ronbinson.cpp
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509593670>
> :
>
> > @@ -0,0 +1,69 @@
> +#include <fstream>
> +
> +using namespace std;
> +
> +ifstream input("robinson.in");
> +ofstream output("robinson.out");
> +
> +int m, n, a[21][21], c, l;
> +
> +void initializeFirstRowAndFirstColumn()
> +{
> +	input >> m >> n >> l >> c;
> +
>
> Close the input stream
> ------------------------------
>
> In robinson/ronbinson.cpp
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509594147>
> :
>
> > +		switch (temp % 4)
> +		{
> +		case 0:
> +			l--;
> +			break;
> +		case 1:
> +			c++;
> +			break;
> +		case 2:
> +			l++;
> +			break;
> +		case 3:
> +			c--;
> +			break;
> +		}
> +	}
>
> Close the output stream
> ------------------------------
>
> In robinson/robinson.in
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509595956>
> :
>
> > @@ -0,0 +1 @@
> +5 64 3 2
>
> Keep the input data
> ------------------------------
>
> In robinson/robinson.out
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509596183>
> :
>
> > @@ -0,0 +1,3 @@
> +592
> +3 2
>
> Keep the output data from campion.edu
> ------------------------------
>
> In robinson/ronbinson.cpp
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#discussion_r509597907>
> :
>
> > @@ -0,0 +1,69 @@
> +#include <fstream>
> +
> +using namespace std;
> +
> +ifstream input("robinson.in");
> +ofstream output("robinson.out");
> +
> +int m, n, a[21][21], c, l;
>
> The declaration of Arrays and matrixes keep on separated lines instead of
> the same line with other simple variables
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adrianursu/campion.edu.ro-arhiva/pull/4#pullrequestreview-514089756>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARLCSYRAPRS4UPLXNMKC5LDSL4WY7ANCNFSM4SYW2UVA>
> .
>

2020-10-22 12:22 UTC, danielursuu requested changes

2020-10-22 12:22 UTC, danielursuu commented on robinson/ronbinson.cpp
> +void modifyPosition(int temporary)
change name of **temporary** in something like nrGrains

2020-10-22 12:22 UTC, danielursuu commented on robinson/ronbinson.cpp
> +void modifyPosition(int temporary)
it is correct to pass temp variable, but temp keeps value of nrGrains

2020-10-22 12:22 UTC, danielursuu commented on robinson/ronbinson.cpp
> +		a[1][i] = n + i - 1;
```suggestion
		a[1][i] = a[i][1];
```

you can write like that, because a[i][1] is already calculated and it is the same, like a mirror

2020-10-22 12:52 UTC, danielursuu approved these changes

2020-10-22 12:53 UTC, merged